services:
  app:
    container_name: xed-website-frontend
    build:
      context: .
      args:
       NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
       NEXT_PUBLIC_API_URL_LOCAL: ${NEXT_PUBLIC_API_URL_LOCAL}
       API_KEY: ${API_KEY}
    restart: always
    env_file:
      - .env
    ports:
      - "30003:3000"
    mem_limit: 512m